; SSLA.INC
; Super Set LibrAry include file
; for making applications

clrscr					equ 0003
dissasembly				equ 0006
dumpregs				equ 0009
flist					equ 0012
fopen					equ 0015
gets					equ 0018
itoa					equ 0021
kbhit					equ 0024
logical_to_hts			equ 0027
memcmp					equ 0030
memcpy					equ 0033
print_byte				equ 0036
print_nibble			equ 0039
print_word				equ 0042
printf					equ 0045
putc					equ 0048
read_sector				equ 0051
reset_drive				equ 0054
scroll					equ 0057
strcmp					equ 0060
strcpyup				equ 0063
strfat12				equ 0066
strlen					equ 0069 ;(nice!)
strup					equ 0072
toupper					equ 0075
update_cursor_to_curr	equ 0078
